meta:
  domainroot: http://www.adopteevee.in # no trailing slash
  title: Adopt Eevee
  description: We found this adorable little pupper abandoned on the street
    in Indiranagar, Banglore, and now she needs a loving home. Click to find
    out more.
  keywords: adopt dog pet puppy pupper doggo pokemon

sass:
  sass_dir: _scss

exclude:
 - CNAME
 - .sass-cache
 - .git
 - bower_components
 - neat
